### PR TITLE
Rewrite plugin to use CoverageTools + Codecov CLI

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by maleadt** [comment]
Great stuff! Have you tried this on a repository that failed before, e.g. Ferrite.jl with an org-wide token again? You can just point to your branch, e.g., https://github.com/JuliaGPU/CUDA.jl/pull/1185/files.

Also x-ref https://github.com/JuliaCI/julia-coverage-buildkite-plugin/pull/3, where I tried this before, where Elliot commented with:

> It's probably worth mentioning that this is a glibc binary, so it's not going to work on musl. I think we can polymorph this a bit to get the alpine binary (instead of linux) to get that to work. I think alpine support is probably necessary, as many people use alpine-based images on CI.

**Comment by fredrikekre** [comment]
Yea I tested on Ferrite and it works. The CI tests here run with both a repo token and a org wide token too.

> It's probably worth mentioning that this is a glibc binary, so it's not going to work on musl. 

They provide musl builds now. What is the canonical way to check for musl libc from julia?

**Comment by maleadt** [comment]
> What is the canonical way to check for musl libc from julia?

Note sure about canonical (cc @giordano), but this seems to work fine:

```julia
julia> Base.BinaryPlatforms.libc(Base.BinaryPlatforms.HostPlatform())
"glibc"
```

**Comment by giordano** [comment]
That's what I'd do, yes.

**Comment by fredrikekre** [comment]
Thanks, added those binaries.

**Review by maleadt — APPROVED** [review]
LGTM.

Should we tag this as `v1.4` or do the significant changes warrant a `v2`?
Previously, the switch to Coverage.jl was part of v1.1, so I guess a minor bump would be fine. We can always revert if it turns out breaking.

**Comment by fredrikekre** [comment]
There are no changes on how the plugin is used to 1.4 is probably ok

**Pull request merged**
